In [1]:
import numpy as np
from math import exp

In [6]:
def sigmod(x):
    return 1 / (1 + exp(-x))

In [3]:
x = np.array([2.5, 0.3, 2.8, 0.5])
x

array([ 2.5,  0.3,  2.8,  0.5])

In [4]:
w = np.ones(4)
w

array([ 1.,  1.,  1.,  1.])

In [5]:
score = x * w
score

array([ 2.5,  0.3,  2.8,  0.5])

In [7]:
p = []
for i in score:
    p.append(sigmod(i))
    print sigmod(i)

0.924141819979
0.574442516812
0.942675824101
0.622459331202


In [8]:
p

[0.9241418199787566, 0.574442516811659, 0.9426758241011313, 0.6224593312018546]

In [10]:
y = [1, -1, 1, 1]

In [17]:
products = 1
j = 0
for i in y:
    if i == 1:
        products = products * p[j]
    else:
        products = products * (1 - p[j])
    j = j + 1
print 'product is %.2f'%products
print products

product is 0.23
0.230765141474


In [15]:
j = 0
derivate = 0
for i in y:
    if i == 1:
        derivate = derivate + x[j] * (1 - p[j])
    else:
        derivate = derivate + x[j] * (0 - p[j])
    j = j + 1
print 'derivate is %.2f'%derivate
print derivate

derivate is 0.37
0.366590721926


# Programming is one thing which I feel Crazy.